name: Hoarder
description: hassio port of [hoarder](https://github.com/hoarder-app/hoarder)
url: https://github.com/moonlight8978/hassio-addons
codenotary: work@bichls.dev
version: 0.24.1
slug: hoarder
image: "ghcr.io/moonlight8978/{arch}-hassio-addon-hoarder"
init: false
boot: auto
arch:
  - aarch64
  - amd64
options:
  NODE_ENV: production
  HOSTNAME: "0.0.0.0"
  NEXTAUTH_SECRET: ""
  CHROMIUM_FLAGS: --disable-software-rasterizer --disable-dev-shm-usage --no-sandbox --disable-gpu --hide-scrollbars
  OPENAI_API_KEY: ""
  OPENAI_BASE_URL: ""
  INFERENCE_TEXT_MODEL: gpt-4o-mini
  INFERENCE_IMAGE_MODEL: gpt-4o-mini
  INFERENCE_LANG: english
  EMBEDDING_TEXT_MODEL: text-embedding-3-small
  CHROMIUM_ENABLED: "true"
  BROWSER_WEB_URL: "http://localhost:9222"
  DISABLE_SIGNUPS: "false"
schema:
  NODE_ENV: list(production)
  HOSTNAME: str
  NEXTAUTH_SECRET: str
  CHROMIUM_FLAGS: str
  OPENAI_API_KEY: str?
  OPENAI_BASE_URL: str?
  INFERENCE_TEXT_MODEL: str?
  INFERENCE_IMAGE_MODEL: str?
  INFERENCE_LANG: str?
  EMBEDDING_TEXT_MODEL: str?
  CHROMIUM_ENABLED: bool?
  BROWSER_WEB_URL: str?
  DISABLE_SIGNUPS: bool?
environment:
  PORT: "3000"
  NEXT_TELEMETRY_DISABLED: "1"
  NEXTAUTH_URL_INTERNAL: "http://localhost:3000"
  DATA_DIR: "/data"
ports:
  3000/tcp: 3000
ports_description:
  3000/tcp: WebUI
webui: "[PROTO:ssl]://[HOST]:[PORT:3000]"
backup_exclude:
  - "*/*.log"
  - "*/queue.db"
  # Screenshots, Videos, ...
  - "*/assets"
# Hoarder use absolute path for assets and APIs, so relative endpoint does not work for ingress
ingress: false
ingress_stream: true
panel_icon: mdi:link-variant-plus
ingress_port: 3000
