services:
  actual:
    build:
      context: actual
      args:
        - BUILD_VERSION=v25.5.0
        - BUILD_FROM=ghcr.io/hassio-addons/base:17.2.2
        - BUILD_ARCH=aarch64
        - BUILD_DATE=2025-03-23
        - BUILD_DESCRIPTION=Test
        - BUILD_NAME=memos
        - BUILD_REF=123
        - BUILD_REPOSITORY=moonlight8978/hassio-addons
    command: yarn start:server
    ports:
      - 5006:5006

  memos:
    build:
      context: memos
      args:
        - BUILD_VERSION=0.24.2
        - BUILD_FROM=ghcr.io/hassio-addons/base:17.2.2
        - BUILD_ARCH=aarch64
        - BUILD_DATE=2025-03-23
        - BUILD_DESCRIPTION=Test
        - BUILD_NAME=memos
        - BUILD_REF=123
        - BUILD_REPOSITORY=moonlight8978/hassio-addons

  hoarder:
    build:
      context: hoarder
      args:
        - BUILD_VERSION=0.23.0
        - BUILD_FROM=ghcr.io/hassio-addons/base:17.2.2
        - BUILD_ARCH=aarch64
        - BUILD_DATE=2025-03-23
        - BUILD_DESCRIPTION=Test
        - BUILD_NAME=hoarder
        - BUILD_REF=123
        - BUILD_REPOSITORY=moonlight8978/hassio-addons
    ports:
      - 3000:3000

  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:124
    restart: unless-stopped
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars

  traefik:
    build:
      context: traefik
      args:
        - BUILD_VERSION=v3.3.4
        - BUILD_FROM=ghcr.io/hassio-addons/base:17.2.2
        - BUILD_ARCH=aarch64
        - BUILD_DATE=2025-03-23
        - BUILD_DESCRIPTION=Test
        - BUILD_NAME=traefik
        - BUILD_REF=123
        - BUILD_REPOSITORY=moonlight8978/hassio-addons
    ports:
      - 9081:8081

  wg-easy:
    build:
      context: wg-easy
      args:
        - BUILD_VERSION=15.0.0-beta.11
        - BUILD_FROM=ghcr.io/hassio-addons/base:17.2.2
        - BUILD_ARCH=aarch64
        - BUILD_DATE=2025-03-23
        - BUILD_DESCRIPTION=Test
        - BUILD_NAME=wg-easy
        - BUILD_REF=123
        - BUILD_REPOSITORY=moonlight8978/hassio-addons
    ports:
      - 51820:51820/udp
      - 51821:51821/tcp
    devices:
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
