name: Actual Budget
description: "Actual Budget (https://actualbudget.org/) addons for Home Assistant"
url: https://github.com/moonlight8978/hassio-addons
codenotary: work@bichls.dev
version: v25.4.0
slug: "actual"
image: "ghcr.io/moonlight8978/{arch}-hassio-addon-actual"
init: false
arch:
  - aarch64
  - amd64
options:
  login_method: password
  allowed_login_methods:
    - password
    - header
schema:
  login_method: list(password|header|openid)?
  allowed_login_methods:
    - match(^(password|header|openid)$)
environment:
  ACTUAL_DATA_DIR: /data
  NODE_ENV: production
ports:
  5006/tcp: 5006
ports_description:
  5006/tcp: WebUI

# The frontend assets use absolute path, it's broken when combine with ingress
# ingress: true
# ingress_port: 5006
# ingress_stream: true
# panel_icon: "mdi:cash-multiple"
