name: Traefik
description: hassio port of [traefik](https://github.com/traefik/traefik)
url: https://github.com/moonlight8978/hassio-addons
codenotary: work@bichls.dev
version: v3.4.0
slug: traefik
image: "ghcr.io/moonlight8978/{arch}-hassio-addon-traefik"
init: false
boot: auto
arch:
  - aarch64
  - amd64
  - armv7
  - i386
options:
  "traefik.yml": |
    providers:
      docker:
        exposedByDefault: false
      file:
        filename: /etc/traefik/dynamic_conf.yml
    api:
      insecure: true
    entryPoints:
      web:
        address: ":80"
      websecure:
        address: ":443"
    accessLog:
      filePath: /data/log/access.log
      fields:
        headers:
          defaultMode: keep
          names:
            Authorization: drop
  "dynamic_conf.yml": |
    http:
      routers: {}
      services: {}
      middlewares: {}
schema:
  "traefik.yml": str
  "dynamic_conf.yml": str
ports:
  80/tcp: 8080
  443/tcp: 8443
  8080/tcp: 8081
ports_description:
  80/tcp: Web entrypoint
  443/tcp: Web Secure (HTTPS) entrypoint
  8080/tcp: Dashboard
webui: "[PROTO:ssl]://[HOST]:[PORT:8081]/dashboard"
ingress: false
ingress_stream: true
panel_icon: mdi:arrow-decision-outline
ingress_port: 8080
ingress_entry: /dashboard
backup_exclude:
  - "*/*.log"
