name: Memos
description: hassio port of [usememos/memos](https://github.com/usememos/memos)
url: https://github.com/moonlight8978/hassio-addons
codenotary: work@bichls.dev
version: 0.24.3
slug: memos
image: "ghcr.io/moonlight8978/{arch}-hassio-addon-memos"
init: false
boot: auto
arch:
  - aarch64
  - amd64
options:
  mode: prod
  addr: 0.0.0.0
  port: 5230
  driver: sqlite
  dsn: ""
  tz: UTC
schema:
  mode: list(prod|dev|demo)
  addr: str
  port: int
  driver: list(sqlite|postgres|mysql)
  dsn: str?
  tz: str?
environment:
  MEMOS_DATA: /data
ports:
  5230/tcp: 5230
ports_description:
  5230/tcp: WebUI
webui: "[PROTO:ssl]://[HOST]:[PORT:5230]"
ingress: false
# ingress_stream: true
panel_icon: mdi:note-edit
ingress_port: 5230
